Mokup implementiert
INF16A/kochbuch-frontend pull request #13
Opened 2017-10-16 13:32 UTC by nxeon

2017-10-16 16:47 UTC, patrick246 requested changes
Das sieht schonmal sehr gut aus, aber kannst du den Header in eine eigene Komponente auslagern, damit man die einfacher einbinden kann und nicht immer neu geladen werden muss? Außerdem ist die Suchleiste auf mobilen Geräten sehr klein, da bitte noch die entsprechenden Bootstrap Klassen einfügen, damit die Suchleiste auf die volle Breite vergrößert wird

2017-10-16 18:30 UTC, nxeon commented
Danke hatte letzte Woche nicht viel Zeit aber habe es schnell angepasst

2017-10-19 06:53 UTC, patrick246 commented
Kannst du die Data-URLs noch rausnehmen und im `asset` Ordner ablegen?

2017-10-25 08:04 UTC, patrick246 commented
Okay, jetzt sind noch zwei Konflikte aufgetreten, die müssen noch resolved werden bevor wir mergen können

2017-10-25 08:13 UTC, patrick246 commented
https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html

2017-10-25 09:49 UTC, nxeon commented
Ist resolved

2017-10-25 18:28 UTC, patrick246 commented
Vermutlich wurde mittlerweile wieder der master geändert, also resolve ich die aktuellen Konflikte und merge dann gleich

2017-10-25 18:41 UTC, patrick246 approved these changes

2017-10-25 18:41 UTC, merged