New recipe
INF16A/kochbuch-frontend pull request #37
Opened 2017-11-05 15:42 UTC by hoernerth

bitte globla css fixen

2017-11-05 16:05 UTC, Paddy3108 submitted a review, later dismissed

2017-11-05 16:05 UTC, Paddy3108 commented on Kochbuch/src/app/rezeptanlegen/rezeptanlegen.model.ts
> +}
bitte die bestehenden Model Klassen benutzen

2017-11-05 20:20 UTC, theresa2403 requested changes
Die Klassen, die in Rezeptanlegen.model.ts sind, sind bereits implementiert und sollten  benutzt werden. 
Dann kann die Klasse gelöscht werden

musst dann ja eigentlich nur die Imports ändern

2017-11-06 09:34 UTC, theresa2403 approved these changes

2017-11-06 09:46 UTC, merged