Navbar erstellt und eingefügt - wer mag kann diese verhübschen :) + Registrierung
INF16A/kochbuch-frontend pull request #4
Opened 2017-09-28 18:55 UTC by Kristin1204

Bitte die entsprechenden Seiten noch als Links einfügen.

Registrierungs-Modal eingefügt.

2017-09-28 20:02 UTC, ArmBeck16 reviewed
- tl;dr Bootstrapklassen verwenden anstatt selbst zu schreiben
- social buttons mit Framework anstatt manuell einzubinden
- Frameworks nicht in index.html einbinden, packages dafür verwenden

2017-09-28 20:02 UTC, ArmBeck16 commented on Kochbuch/src/app/app.component.css
> +/* Facebook */
Besser Library für Social Buttons verwenden anstelle Icons manuell zum Repo hinzuzufügen, z.B.
https://www.npmjs.com/package/bootstrap-social

2017-09-28 20:02 UTC, ArmBeck16 commented on Kochbuch/src/index.html
> +  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></
Skripte wie Bootstrap, PopperJS etc.. sollten nicht manuell eingebunden werden.

2017-09-28 20:02 UTC, ArmBeck16 commented on Kochbuch/src/app/app.component.css
> +  background: url('img/instagram_back.png') no-repeat;
Für Gradienten sollte  CSS3 anstatt Bilder verwendet werden (hier radial gradient) https://www.w3schools.com/css/css3_gradients.asp

2017-09-28 20:02 UTC, ArmBeck16 commented on Kochbuch/src/app/app.component.html
> +                <div class="checkbox">
die Checkboxklasse wird nicht in der CSS verwendet, also sollte die Bootstrapklasse dafür verwendet werden
http://getbootstrap.com/docs/4.0/components/forms/#checkboxes-and-radios

2017-09-28 20:11 UTC, patrick246 requested changes
Hab mal die Änderungen durchgeguckt und ein paar Kommentare zum Code hinzugefügt

2017-09-28 20:11 UTC, patrick246 commented on Kochbuch/src/app/app.component.css
> +.loginBtn {
Diese Buttons sollten auch als Bootstrap Buttons gemacht werden, eigene Styles können dann auf diesen Styles angewendet werden. Das sorgt für ein einheitliches Design mit anderen Buttons und dass diese in allen Browsern möglichst gleich aussehen.

2017-09-28 20:11 UTC, patrick246 commented on Kochbuch/src/app/app.component.html
> +<!-- Modal für die Registrierung, wird über jQuery aufgerufen -->
NgBootstrap bietet einen Angular Service um Modaldialoge zu starten. https://ng-bootstrap.github.io/#/components/modal/examples Die Verwendung von NgBootstrap sorgt für ein besseres Zusammenspiel mit Angular.

Außerdem sollte der Registrierungsdialog in eine eigene Komponente ausgelagert werden, die App-Komponente sollte sich nicht um die Registrierung kümmern. Dadurch wird eine Überladung der App-Komponenten Code-Datei verhindert, da sonst der Formularcode in dieser geschrieben werden müsste.

2017-09-28 20:11 UTC, patrick246 commented on Kochbuch/src/index.html
> +
JS-Skripte sollten über NPM installiert werden, damit diese mit Webpack minifiziert und gebundlet werden können.

2017-09-28 20:11 UTC, patrick246 commented on Kochbuch/src/app/app.component.html
> +            <label>Geschlecht</label>
Die Radio Buttons und Checkboxen sollten auch mit Bootstrap gestyled werden.

2017-09-28 20:11 UTC, patrick246 commented on Kochbuch/src/app/app.component.html
> +            <label>Name</label>
Mit der CSS-Klasse `form-group` können einzelne Zeilen eines Formulars zusammengefasst werden: https://v4-alpha.getbootstrap.com/components/forms/#form-groups Damit ist kein `row` und `col-*` notwendig

2017-09-28 20:11 UTC, patrick246 commented on Kochbuch/src/app/app.component.html
> +                <input type="checkbox" name="vegetraisch" id="vegetraisch" autocomplete="off"><label for="vegetraisch">vegetraisch</label>
Rechtschreibfehler: vegetarisch

2017-10-08 16:35 UTC, philippsteigler submitted a review, later dismissed

2017-10-08 22:26 UTC, patrick246 submitted a review, later dismissed

2017-10-08 22:30 UTC, patrick246 commented
Folgendes sollte in Zukunft noch geändert werden: 
* Bilddateien, die nicht mehr benötigt werden entfernen
* body padding rausnehmen (bringt sowieso nichts)

Da es aber bereits Montag ist, würde ich sagen, ich merge das und wir fixen das irgendwann später, damit die Anwendung auch nach was aussieht.

2017-10-08 22:36 UTC, merged