Beutzer Profil Info
INF16A/kochbuch-frontend pull request #5
Opened 2017-09-28 20:28 UTC by CROBG

2017-09-29 06:41 UTC, patrick246 requested changes
Code compiliert nicht, bitte anpassen:
```
ERROR in C:/Users/patrick/Documents/GitHub/kochbuch-frontend/Kochbuch/src/app/app-routing.module.ts (12,
3): ',' expected.

ERROR in C:/Users/patrick/Documents/GitHub/kochbuch-frontend/Kochbuch/src/app/app.module.ts (16,5): ','
expected.

ERROR in C:/Users/patrick/Documents/GitHub/kochbuch-frontend/Kochbuch/src/app/app.module.ts (16,5): ','
expected.

ERROR in C:/Users/patrick/Documents/GitHub/kochbuch-frontend/Kochbuch/src/app/app-routing.module.ts (12,
3): ',' expected.
```

2017-09-29 06:41 UTC, patrick246 commented on Kochbuch/src/app/app-routing.module.ts
>    {path: 'rezeptansicht', component: RezeptansichtComponent}
Hier fehlt ein Komma am Ende

2017-09-29 06:41 UTC, patrick246 commented on Kochbuch/src/app/app.module.ts
>      RezeptansichtComponent
Hier fehlt ein Komma am Ende

2017-09-29 06:42 UTC, patrick246 commented on Kochbuch/src/app/user-profile/user-profile.component.html
> +        <img class="img-rounded" src="https://www.1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png" />
Bilder bitte lokal einbinden, das Bild kann jeden Moment heruntergenommen werden

2017-09-29 07:21 UTC, CROBG commented
Oops, habs jetzt gefixed

2017-09-29 08:22 UTC, patrick246 requested changes
Zusammenfassung:
Bootstrap 3 => 4
Inline Styles auslagern
Bilddatei verschieben

2017-09-29 08:22 UTC, patrick246 commented on Kochbuch/src/app/user-profile/user-profile.component.html
> +    <div style="min-height: 50em; background: gray;" class="col-md-6">
Inline-Styles bitte vermeiden, entweder eine geeignete Bootstrap-Klasse suchen oder in die Style Datei auslagern

2017-09-29 08:22 UTC, patrick246 commented on Kochbuch/src/app/user-profile/user-profile.component.html
> +<div class="userProfile">
Der Code hier basiert auf Bootstrap 3, wir verwenden aber Bootstrap 4: https://getbootstrap.com/docs/4.0/

2017-09-29 08:22 UTC, patrick246 commented on Kochbuch/src/app/user-profile/user-profile.component.html
> +    <div class="col-md-6 well well-sm">
Hier wird zum Beispiel die `well` Klasse verwendet, die in Bootstrap 4 durch die Card Komponente ersetzt wurde: https://getbootstrap.com/docs/4.0/migration/#components

2017-09-29 08:22 UTC, patrick246 commented on Kochbuch/src/app/user-profile/user-profile.component.html
> +        <img class="img-rounded" src="assets/user.png" />
Die Bilddatei liegt im falschen Pfad, diese muss unter `src/assets` liegen

2017-10-02 10:05 UTC, patrick246 commented
Okay, jetzt müssen noch die Konflikte gegenüber master aufgelöst werden, d.h. auf deinem Branch bitte master reinmergen und dann resolven und pushen

2017-10-04 19:53 UTC, merged

2017-10-04 19:54 UTC, patrick246 commented
Ich hab noch eine Datei verschieben müssen (die User Datei war unter user-profile im asset Ordner, nicht im app Ordner), aber ansonsten ist das jetzt gemergt.